dist: xenial
language: python
cache:
  pip: true
python:
- "3.7"
env:
- PIPENV_VERBOSITY=-1
before_install:
- pip install pipenv
install:
- pipenv sync -d
script:
- pipenv run pytest --pyargs qvibe --cov=./qvibe
after_success:
- bash <(curl -s https://codecov.io/bash)