dist: xenial
language: python
cache:
  pip: true
python:
- "3.7"
before_install:
- pip install pipenv
install:
- pipenv sync -d
script:
- PYTHONPATH=./qvibe-recorder pipenv run pytest --pyargs qvibe-recorder --cov=./qvibe-recorder
after_success:
- bash <(curl -s https://codecov.io/bash)